### ISSUE TITLE
#1 create dashboard-page

### ISSUE THREAD

**Issue by GregOnOff** [GregOnOff/capstone-project#1]
## Value Proposition
​
**As a** :  User
**I want to** see a list of my wishlist Items
**so that I**  see the most important details of my desired wishlist item
​
## Description

![Image](https://user-images.githubusercontent.com/113910034/201952850-72a7c23b-7d3d-419b-80b7-7b461e9c3566.PNG)

​
## Acceptance Criteria
​

- [ ] The landing page should contain a Header with an icon & app-name
- [ ] The landing page should also contain a Headline for the products displayed 
- [ ] The landing page should contain example wishlist items
- [ ] Each wishlist item should be displayed on its own as a card
- [ ] Every single item should contain only major details of the product

​
## Tasks
​
- [ ] create `Header` component
- [ ] create `Wishlist` component
- [ ] create `WishlistItem` component
- [ ] create `Headline` component
- [ ] add `dummy-data` in a separate file
- [ ] fill the `WishlistItem` with dummy data from `dummy-data` 
- [ ] add icons for `Header` and 'consideration-time'
- [ ] add initial styling to the components

## Complexity 

S
