### ISSUE TITLE
#2 add new item

### ISSUE THREAD

**Issue by GregOnOff** [GregOnOff/capstone-project#2]
## Value Proposition
​
**As a** :  User
**I want to** add new items to my List
**so that I**  can expand my list 
​
## Description

![Image](https://user-images.githubusercontent.com/113910034/202137528-f217b887-b5aa-458b-bf6f-316872a772d4.PNG)

​
## Acceptance Criteria
​

- [ ] The landing page should contain an add button
- [ ] The add button should lead to a form 
- [ ] The form should contain two buttons for saving and exit the form
- [ ] The save button should update the data 
- [ ] The exit button should led back to details page
- [ ] The form should contain input fields for name, price, link & category
- [ ] The new item should be displayed at the landing page on save

​
## Tasks
​
- [ ] create a `addItemForm` with all properties the user can 
- [ ] create `backButton` 
- [ ] create a `saveButton`
- [ ] write a function for the `back-Button` that leads back to details page
- [ ] write a function for the `saveButton` that replaces the data in `dummy-data`
- [ ] write function that appends the data by clicking `saveButton`  as an item card to the wishlist 
- [ ] add initial styling to the components

## Complexity 

L

**Comment by JessicaLoers** [comment]
Hi @GregOnOff ✌️
well done. I have some suggestions:

**Value Proposition**
As a `:` User --> _just a little typo_
I want to add new items to my **whishlist** --> _is more descriptive_ 
so that I have my desired items listed together in one place, which gives me a better overview. --> _here, too, you can be a bit more descriptive_

**Acceptance Criteria**
-[ ] The ~exit~ **cancel** button should led back to details page --> _it's best practice to be consistent in the naming (see wireframe)_
Some questions:
- what about validations, required inputs
- do I get feedback that my desired item has been added? (e.g. modal with submit message for x sec.)
- what happens after submitting the form? (e.g.  redirection to landingpage)

**Tasks**

-[ ] create a addItemForm with all properties the user can --> _missing verb_
-[ ] create backButton --> Looks like a button but is actually a next/link.

-[ ] write a function for the saveButton that replaces the data in dummy-data
-[ ]  write function that appends the data by clicking saveButton as an item card to the wishlist
-----> _Fortunately, we are in react land, so you can do these two tasks in one go_.

**If you have any question -  feel free to ask** 

by the way: 399.99 € is a good deal🐼

**Comment by WilhelmAlfke** [comment]
hey @GregOnOff, I didn't see that this had already been reviewed, since your request wasn't labeled "updated". That confused me for a while.
Regarding your changes, they look fine to me. 

this vestment seems to be an excellent investment. 😍
