### ISSUE TITLE
#3 add a details page

### ISSUE THREAD

**Issue by GregOnOff** [GregOnOff/capstone-project#3]
## Value Proposition
​
**As a** :  User
**I want to** see further details of the listed item
**so that I**  get more information about the item
​
## Description

![Image](https://user-images.githubusercontent.com/113910034/202001569-e428c484-ee25-4303-afe8-391ad7b2c11f.PNG)

​
## Acceptance Criteria
​

- [ ] The details page should contain the already given information of the card on the landing page
- [ ] The details page should display a placeholder image 
- [ ] On the details page a link to the item should be displayed and clickable
- [ ] The page also should contain a Button for going back to landing page

​
## Tasks
​
- [ ] create `WishlistItemDetails` component
- [ ] create `back-Button` 
- [ ] write a function for the `back-Button` 
- [ ] fill the `WishlistItemDetails` with more dummy data from `dummy-data` 
- [ ] add initial styling to the components

## Complexity 

M

**Comment by ahohnsen** [comment]
Hey Greg,

Here are my suggestions:

**Value Proposition:**
There is a small typo :)

_As a user
I want to have a detailed view of my wishlist items
so that I get more information about the item_

Acceptance Criteria:
Here is missing how the user can reach the details page :)
