### ISSUE TITLE
#5 questioning the purchase

### ISSUE THREAD

**Issue by GregOnOff** [GregOnOff/capstone-project#9]
## Value Proposition
​
**As a**  User
**I want to** be able to delete certain items in the wishlist 
**so that I**  can get rid of unwanted items before the time to concider is over
​
## Description

![Image](https://user-images.githubusercontent.com/113910034/205272725-ee57d14b-f530-441c-b0b6-d2e54e086fed.PNG)

​
## Acceptance Criteria
​

- [ ] The Details Page should contain a delete button
- [ ] When clicked on 'delete' a modal should pop up 
- [ ] In the modal the user should be asked if he is sure about deleting the item
- [ ] The modal should also contain two buttons for confirm and cancel.
- [ ] the cancel button should close the modal
- [ ] The confirm button should delete the whole item from my wishlist
- [ ] A message should appear when the data is successfully deleted
- [ ] The user should be redirected to the landing page after succesful delete

​
## Tasks
​
- [ ] create a `delete` button inside the details page 
- [ ] create a modal with `cancel` and `confirm` button
- [ ] create delete function for the button that affects local storage data
- [ ] add snackbar component to the details page
- [ ] add initial styling to the components

## Complexity 

M
